### ISSUE TITLE
TypeError: unusable when creating a new project

### ISSUE THREAD

**Issue by adarnimrod** [elastic/synthetics#920] opened 2024-04-27 13:45 UTC
Hello,

I'm unable to create a new project. When running `npx @elastic/synthetics init projects-test`, after entering the Kibana URL and the API key I get the error `TypeError: unusable`. The API key is for private locations, Elasticsearch and Kibana are self-hosted and behind a VPN but I'm connected to the VPN.

Elasticsearch version: 8.11.3
Kibana version: 8.11.3
Synthetics version: 1.9.0
Node version: 21.7.3

**Comment by vigneshshanmugam** [comment] 2024-04-29 04:59
Seems like a duplicate of #885, Will try to repro again and do a fix.

**Comment by adarnimrod** [comment] 2024-04-30 14:38
@vigneshshanmugam if you're asking about errors with the synthetics CLI, the entire output is:
```
$ npx @elastic/synthetics init projects-test
> Initializing Synthetics project in 'projects-test'
✔ Enter Elastic Kibana URL or Cloud ID · https://kibana.schoolinks.com/
✔ What is your API key · ************************************************************
TypeError: unusable
```
If you're asking about the logs from Kibana, I tailed the logs and retried and nothing was outputted (log level set to `warn`).

**Closed** 2024-05-03 15:16 UTC
Labels: bug

**Comment by adarnimrod** [comment] 2024-05-03 15:43
@vigneshshanmugam I see that the PR was merged. How can I test it? Do I need to wait for a release?

**Comment by vigneshshanmugam** [comment] 2024-05-03 18:23
@adarnimrod Once the new release is our, you should be able to test it. I am trying to fix the CI error that we are dealing with the release, once its fixed a new release will be out.
