### ISSUE TITLE
Add Soft Assertions

### ISSUE THREAD

**Issue by zx8086** [elastic/synthetics#875] opened 2023-12-17 04:15 UTC
Would be great if we could do soft assertions like in Playwright as shown in the example / link below.

https://playwright.dev/docs/test-assertions#soft-assertions

`// Make a few checks that will not stop the test when failed...
await expect.soft(page.getByTestId('status')).toHaveText('Success');
await expect.soft(page.getByTestId('eta')).toHaveText('1 day');

// ... and continue the test to check more things.
await page.getByRole('link', { name: 'next page' }).click();
await expect.soft(page.getByRole('heading', { name: 'Make another order' })).toBeVisible();`

```[tasklist]
### Tasks
```

**Comment by shahzad31** [comment] 2023-12-19 10:22
@zx8086 i think we already supports those assertions from playwright, which versio of synthetics are you using?

https://github.com/elastic/synthetics/pull/812

**Comment by shahzad31** [comment] 2023-12-19 10:29
`Note that soft assertions only work with Playwright test runner.
` 

i now get it, i think it needs some handling on our runner to make it work

**Comment by vigneshshanmugam** [comment] 2024-04-22 18:45
We added a way to do soft assertion on the Step level by marking the step with .soft. Failure of soft step will not skip rest of the steps in the journey.
```ts
journey('test journey', ({}) => {
  step.soft('step 1', async () => {
   // errored step
    expect('').toEqual('hello');
  });
    // step 2 will still run
  step('step 2', async () => {
    // errored step
    expect('').toEqual('hello');
  });
});
```

From version 1.7.0 - https://github.com/elastic/synthetics/releases/tag/v1.7.0

**Comment by vigneshshanmugam** [comment] 2024-05-15 16:51
@zx8086 Could you tell the stack/heartbeat version used for testing this? You might need to upgrade to 8.13.x if its an older version.

**Comment by vigneshshanmugam** [comment] 2024-05-16 17:38
@zx8086 Interesting, I just did ran a fake broken test to see if I can repro this behaviour, unfortunately I cant. 

```ts
  step('step 1', async () => {
    browser.newContext();
    expect(page).toHaveTitle('blah');
  });

  step.soft('step 2', async () => {
    // errored step
    expect('').toEqual('hello');
  });
  // step 3 will still run
  step('step 3', async () => {
    console.log('step 3');
  });
```

<img width="1439" alt="Screenshot 2024-05-16 at 10 34 24 AM" src="https://github.com/elastic/synthetics/assets/3902525/373eb5a6-f639-42d9-86fc-68cf9911b8c6">

Can you run this test in a Public synthetics location and see if there is a difference from your private location. Also, if you can share a script that exposes this behaviour - I can double check on my side. Thanks.

**Comment by shahzad31** [comment] 2024-09-30 16:35
@zx8086 can you please try this again? i tried your script and even though first step fails, the 2nd step still runs.

**Comment by vigneshshanmugam** [comment] 2024-10-01 19:01
Thanks for confirming @zx8086 Closing the issue as its working as intended.

**Closed by vigneshshanmugam** 2024-10-01 19:01 UTC
Labels: enhancement
